# Generated by Django 5.1.7 on 2025-03-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('player_1', 'player_2')},
        ),
    ]
